FROM ubuntu:22.04

# Install essential packages
RUN apt-get update
RUN apt-get install -y python3 python3-pip
RUN pip install --no-cache-dir -U pip
RUN pip install --no-cache-dir grpcio==1.48.* grpcio-tools
RUN pip install --no-cache-dir numpy

COPY client client
COPY proto proto

RUN cd /proto && python3 -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. tunnel.proto
CMD ["python3", "client/client.py"]