FROM ubuntu:22.04 as build

# Install essential packages
RUN apt-get update
RUN apt-get install -y python3 python3-pip
RUN pip install --no-cache-dir -U pip
RUN pip install --no-cache-dir torch==1.12.1 torchvision==0.13.1

COPY example/gen_onnx.py .
RUN python3 gen_onnx.py


FROM ubuntu:22.04 as binary
COPY --from=build /model.onnx /model.onnx

